#!/bin/bash
DIR="`dirname \"$0\"`"
DIR="`( cd \"$DIR\" && readlink -f $(pwd) )`"
export BABL_PATH=$(readlink -f "$DIR/usr/lib//x86_64-linux-gnu/babl-0.1")
export GEGL_PATH=$(readlink -f "$DIR/usr/lib/x86_64-linux-gnu/gegl-0.3/")
PATH="$DIR/usr/bin" exec laidout "$@"
