.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LAIDOUT 1 "September 4, 2006"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
.B Laidout
Version 0.07.1, for laying out books
.SH SYNOPSIS
.B laidout
.RI [ options ] " files" ...
.br
.SH DESCRIPTION
\fBLaidout\fP can be used to lay out pictures and more into cut and folded
books. For instance, from 11x17 inch master sheets, one can cut and fold in
such a way that produces 3 cute little 5.5x5.6 inch booklets.

Anectotal studies among the developers have shown that people who use
Laidout have more friends and their documents get laid out much more quickly 
than with many other programs.

Please be advised that this is a very early version of Laidout. There is a mailing
list and a page describing various bugs and deficiencies at the Laidout website:
http://www.laidout.org. Only you can help stop bugs.

Donations are encouraged! Money and code, that is, not bugs.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options and exit.
.TP
.B \-v, \-\-version
Show version of program and exit.
.TP
.B \-\-file\-format file
Write out a pseudocode mockup of the Laidout file format to file then exit.
Will fail if file exists already.
.TP
.B \-n, \-\-new \fISPECIFICATION\fI
Create a new document, bypassing the new document dialog. You can specify
a comma separated list of attributes describing the paper size, orientation,
imposition, and number of pages. So for instance a 40 page booklet on folded 
legal sized paper oriented as landscape would be specified with:

.B laidout \-n 'legal,landscape,booklet,40'
.TP
.B \-t, \-\-template \fItemplate_name\fI
Open laidout from this template. If the name does not start with "../", "./",
or "/", then it looks in your $HOME/.laidout/(version)/templates directory.
These templates can be any valid Laidout document file. The file is loaded,
and its file location cleared so that you will be forced to enter a new
location for it when you try to save it.

If you have default_template set to something in your laidoutrc file, such as with
a line like "default_template default" then when you start Laidout with
no arguments, that template will be loaded (in this case templates/default
will be loaded), rather then prompting you through the new document dialog.


.SH QUICK KEY REFERENCE

A + means shift, and a ^ means control.

Window gutter:
   ^left-click   Split window mouse was in last
   +left-click   Join to adjacent window
   right-click   Get a menu to split, join, or change


In a viewer:
   'D'        toggle drawing of axes for each object
   's'        toggle showing of the spread (shows only limbo)
   'm'        move current selection to another page, pops up a dialog ***imp me!
   ' '        center the spread
   +' '       center the page
   '=' or '+' zoom in around mouse
   '-'        zoom out around mouse
   'o'        clear any display rotation
   'O'        center the viewer on the viewer origin

   left       previous tool
   right      next tool
   ','        previous object
   '.'        next object  
 +^'a'        deselect all currently selected objects\n"
   '<'        previous page  
   '>'        next page   
 
   'T' or left   prev tool 
   't' or right  next tool
   '<'           previous page 
   '>'           next page
   ^'s'          save file
   ^+'s'         save as -- just change the file name?? (not imp)
   F1            popup this quick reference
   F2            popup an About window
   F5            popup new spread editor window

    // these are like inkscape
   pgup      raise selection by 1 within layer
   pgdown    lower selection by 1 within layer
   home      bring selection to top within layer
   end       drop selection to bottom within layer
  

ObjectInterface:
  'c'          toggle if drag resizes from center or opposite edge
  'd'          toggle the showing of decorations
  'n'          normalize, that is, make norm(xaxis)==norm(yaxis) and y=transpose(x)
  'N'          like 'n', but also clear rotation
  bksp or del  remove whichever of center, rotation handle, or shear handle
                 is selected
  ^left-click  define a center, rotation handle, or shear handle
  
  plain click on a center, rotation handle, or shear handle, then press control
    to move the point, rather than modify the object
  

SpreadEditor:
   ' '    Center with all little spreads in view
   'c'    toggle where the page labels go
   'm'    toggle mark of current page
   'M'    reverse toggle mark of current page
   't'    toggle drawing of thumbnails
   'A'    toggle how to arrange the spreads
  ^'A'    force arranging the spreads using current arrange style
   'p'    *** for debugging thumbs


ImageInterface:
  'n'      normalize, that is, make norm(xaxis)==norm(yaxis) and y=transpose(x)
  'N'      like 'n', but also clear rotation
  'd'      Toggle drawing decorations
  'f'      Toggle writing the filename next to the image


ColorPatchInterface:
  'w'    warp the patch to an arc, rows are at radius, cols go from center
  'm'    toggle between drawing just the grid, or draw full colors.
  'a'    select all points, or deselect all if any are selected
  'y'    constrain to y changes, or release the constraint
  'x'    constrain to x changes, or release the constraint
  'o'    decrease how much to recurse for rendering screen preview
  'O'    increase how much to recurse for rendering screen preview
  'R'    increase how many rows to divide each row into
 ^'R'    decrease how many rows to divide each row into
  'r'    subdivide rows
  'c'    subdivide columns
  'C'    increase how many columns to divide each column into
 ^'C'    decrease how many columns to divide each column into
  's'    subdivide rows and columns
  'z'    reset to rectangular
  'w'    warp the patch to an arc, rows are at radius, cols go from center
  'd'    toggle decorations
  'h'    select all points adjacent horizontally to current points
  'v'    select all points adjacent vertically to current points
  'b'    toggle which control points are available
  'B'    reverse of 'b'
  'j'    toggle smooth node editing (j for jagged)
  '1'    select corners:  0,0  0,3  3,0  3,3
  '2'    select center controls: 1,1  1,2  2,1  2,2
  '3'    select edge controls: 0,1  0,2  1,0  2,0  1,3  2,3  3,1  3,2
  '4'    select top and bottom controls: 1,0  2,0  1,3  2,3
  '5'    select left and right controls: 0,1  0,2  3,1  3,2
  '8'    select a 3x3 group of points around each current point



GradientInterface:
  'r'   Radial gradient
  'l'   Linear Gradient
  'f'   flip the order of the colors
  'd'   Toggle showing of decorations
  left  Select next point
  right Select previous point
  
  shift-left-click: add a new color spot



PathInterface:
  'o'    Select the next pathop.
  left   Roll the curpoints one step previous.
  right  Roll the curpoints one step next.
  'A'    Toggle whether to add points after or before
  'a'    Select all if none selected, else deselect all
  'c'    Toggle closed path
  'b'    Start a new PathsData
  delete or bksp: Delete currently selected points.
  'd'    Toggle displaying of decorations
  '?'    Show some kind of help somewhere....?
  'p'    Like a, but only in current part of a compound path



.br
The program is documented fully by the doxygen documention found in the source.
.SH COPYRIGHT
This program is released under the GPL v2.
.SH AUTHOR
\fBLaidout\fP was written with varying degrees of success by 
\fBTom Lechner\fP <tomlechner@users.sourceforge.net>,
who is still currently the only developer, and who would probably rather be
drawing cartoons (http://www.tomlechner.com).
